/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

package com.huawei.elibri.java.service.repository;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.ObjectTypeInfo;
import com.huawei.elibri.java.service.model.AgeGroup;
import com.huawei.elibri.java.service.model.Author;
import com.huawei.elibri.java.service.model.Bookmark;
import com.huawei.elibri.java.service.model.Books;
import com.huawei.elibri.java.service.model.Interest;
import com.huawei.elibri.java.service.model.Profile;
import com.huawei.elibri.java.service.model.ProfileInterest;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * Definition of ObjectType Helper.
 *
 * @since 2020-12-11
 */

public final class ObjectTypeInfoHelper {
    private static final  int FORMAT_VERSION = 2;
    private static final int OBJECT_TYPE_VERSION = 44;

    /**
     * Get the table object info from cloud Db
     *
     * @return table object
     */
    public static ObjectTypeInfo getObjectTypeInfo() {
        ObjectTypeInfo objectTypeInfo = new ObjectTypeInfo();
        objectTypeInfo.setFormatVersion(FORMAT_VERSION);
        objectTypeInfo.setObjectTypeVersion(OBJECT_TYPE_VERSION);
        List<Class<? extends CloudDBZoneObject>> objectTypeList = new ArrayList<>();
        Collections.addAll(objectTypeList, Interest.class, Bookmark.class,
                AgeGroup.class, Author.class, ProfileInterest.class,
            Books.class, Profile.class);
        objectTypeInfo.setObjectTypes(objectTypeList);
        return objectTypeInfo;
    }
}
