/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.elibri.kotlin.service.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType AgeGroup.
 *
 * @since 2021-03-24
 */
@PrimaryKeys({"ageId"})
public class AgeGroup extends CloudDBZoneObject {
    private Integer ageId;

    private String ageGroup;

    private String maxAge;

    private String minAge;

    public AgeGroup() {
        super(AgeGroup.class);
    }

    public void setAgeId(Integer ageId) {
        this.ageId = ageId;
    }

    public Integer getAgeId() {
        return ageId;
    }

    public void setAgeGroup(String ageGroup) {
        this.ageGroup = ageGroup;
    }

    public String getAgeGroup() {
        return ageGroup;
    }

    public void setMaxAge(String maxAge) {
        this.maxAge = maxAge;
    }

    public String getMaxAge() {
        return maxAge;
    }

    public void setMinAge(String minAge) {
        this.minAge = minAge;
    }

    public String getMinAge() {
        return minAge;
    }

}
