/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.elibri.kotlin.service.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType Bookmark.
 *
 * @since 2021-03-24
 */
@PrimaryKeys({"bookmarkid"})
public class Bookmark extends CloudDBZoneObject {
    private String emailid;

    private Integer pageno;

    private Integer bookmarkid;

    private String bookname;

    private Integer bookId;

    public Bookmark() {
        super(Bookmark.class);
    }

    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }

    public String getEmailid() {
        return emailid;
    }

    public void setPageno(Integer pageno) {
        this.pageno = pageno;
    }

    public Integer getPageno() {
        return pageno;
    }

    public void setBookmarkid(Integer bookmarkid) {
        this.bookmarkid = bookmarkid;
    }

    public Integer getBookmarkid() {
        return bookmarkid;
    }

    public void setBookname(String bookname) {
        this.bookname = bookname;
    }

    public String getBookname() {
        return bookname;
    }

    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    public Integer getBookId() {
        return bookId;
    }

}
