/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

package com.huawei.elibri.kotlin.service.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType Books.
 *
 * @since 2020-12-11
 */
@PrimaryKeys({"bookId"})
public class Books extends CloudDBZoneObject {
    private Integer bookId;

    private String imageUrl;

    private Integer authorId;

    private String description;

    private Integer integerId;

    private Integer ageGroup;

    private String interest;

    @NotNull
    @DefaultValue(stringValue = "The End of Living")
    private String bookName;

    @NotNull
    @DefaultValue(stringValue = "https://www.google.com")
    private String bookUrl;

    private Boolean isPaid;

    public Books() {
        super(Books.class);
        this.bookName = "The End of Living";
        this.bookUrl = "https://www.google.com";
    }

    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    public Integer getBookId() {
        return bookId;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    public Integer getAuthorId() {
        return authorId;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return description;
    }

    public void setIntegerId(Integer integerId) {
        this.integerId = integerId;
    }

    public Integer getIntegerId() {
        return integerId;
    }

    public void setAgeGroup(Integer ageGroup) {
        this.ageGroup = ageGroup;
    }

    public Integer getAgeGroup() {
        return ageGroup;
    }

    public void setInterest(String interest) {
        this.interest = interest;
    }

    public String getInterest() {
        return interest;
    }

    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    public String getBookName() {
        return bookName;
    }

    public void setBookUrl(String bookUrl) {
        this.bookUrl = bookUrl;
    }

    public String getBookUrl() {
        return bookUrl;
    }

    public void setIsPaid(Boolean isPaid) {
        this.isPaid = isPaid;
    }

    public Boolean getIsPaid() {
        return isPaid;
    }

}
