/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */

package com.huawei.elibri.java.service.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType Profile.
 *
 * @since 2020-12-11
 */
@PrimaryKeys({"emailid"})
public class Profile extends CloudDBZoneObject {
    private String emailid;

    @NotNull
    @DefaultValue(stringValue = "null")
    private String name;

    @NotNull
    @DefaultValue(byteValue = 0)
    private Byte age;

    @NotNull
    @DefaultValue(booleanValue = false)
    private Boolean gender;

    @NotNull
    @DefaultValue(booleanValue = false)
    private Boolean subscription;

    public Profile() {
        super(Profile.class);
        this.name = "null";
        this.age = 0;
        this.gender = false;
        this.subscription = false;
    }

    public void setEmailid(String emailid) {
        this.emailid = emailid;
    }

    public String getEmailid() {
        return emailid;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setAge(Byte age) {
        this.age = age;
    }

    public Byte getAge() {
        return age;
    }

    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    public Boolean getGender() {
        return gender;
    }

    public void setSubscription(Boolean subscription) {
        this.subscription = subscription;
    }

    public Boolean getSubscription() {
        return subscription;
    }

}
